/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.UserInterface.LoginPage;

/**
 *
 * @author guill
 */
public class InterfaceBorda extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceBorda
     */
    public InterfaceBorda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupBordas = new javax.swing.ButtonGroup();
        PanelIntBorda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RButtonCatupiry = new javax.swing.JRadioButton();
        RButtonCheddar = new javax.swing.JRadioButton();
        RButtonChocPreto = new javax.swing.JRadioButton();
        RButtonChocBranco = new javax.swing.JRadioButton();
        ButtonVoltar = new javax.swing.JButton();
        ButtonProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Borda");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        ButtonGroupBordas.add(RButtonCatupiry);
        RButtonCatupiry.setText("Catupiry");
        RButtonCatupiry.setContentAreaFilled(false);

        ButtonGroupBordas.add(RButtonCheddar);
        RButtonCheddar.setText("Cheddar");
        RButtonCheddar.setContentAreaFilled(false);

        ButtonGroupBordas.add(RButtonChocPreto);
        RButtonChocPreto.setText("Chocolate Preto");
        RButtonChocPreto.setContentAreaFilled(false);

        ButtonGroupBordas.add(RButtonChocBranco);
        RButtonChocBranco.setText("Chocolate Branco");
        RButtonChocBranco.setContentAreaFilled(false);

        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });

        ButtonProximo.setText("Proximo");
        ButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIntBordaLayout = new javax.swing.GroupLayout(PanelIntBorda);
        PanelIntBorda.setLayout(PanelIntBordaLayout);
        PanelIntBordaLayout.setHorizontalGroup(
            PanelIntBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIntBordaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(PanelIntBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RButtonChocBranco)
                    .addComponent(RButtonChocPreto)
                    .addComponent(RButtonCheddar)
                    .addComponent(RButtonCatupiry)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(PanelIntBordaLayout.createSequentialGroup()
                .addComponent(ButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonProximo))
        );
        PanelIntBordaLayout.setVerticalGroup(
            PanelIntBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIntBordaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(RButtonCatupiry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RButtonCheddar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RButtonChocPreto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RButtonChocBranco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(PanelIntBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonVoltar)
                    .addComponent(ButtonProximo)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelIntBorda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelIntBorda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
        
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void ButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProximoActionPerformed
        
        InterfaceTamanho interfaceTamanho = new InterfaceTamanho();
        interfaceTamanho.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ButtonProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceBorda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceBorda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceBorda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceBorda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBorda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroupBordas;
    private javax.swing.JButton ButtonProximo;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JPanel PanelIntBorda;
    private javax.swing.JRadioButton RButtonCatupiry;
    private javax.swing.JRadioButton RButtonCheddar;
    private javax.swing.JRadioButton RButtonChocBranco;
    private javax.swing.JRadioButton RButtonChocPreto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
